services:
  mariadb:
    build: ./containers/MariaDB

    container_name: mariadb

    restart: always

    env_file: .env

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - inception

  wordpress:
      build: ./containers/Wordpress

      container_name: wordpress

      restart: always

      env_file: .env

      ports:
        - "8080:80"

      volumes:
        - wordpress_data:/var/www/html

      networks:
      - inception
    
      depends_on:
      - mariadb
    
volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception: